### ISSUE TITLE
Revise hepatitis terms in EFO

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/efo#549]
EFO has
EFO > HP:0012115 hepatitis (a phenotype)
EFO > EFO:0004196 viral human hepatitis infection (a disease, with 4 children)
- [x] This duplication may need to be addressed. (MONDO has MONDO:0002251 hepatitis with child MONDO:0006011 viral hepatitis) (Moved to https://github.com/ebispot/efo/issues/471#issuecomment-531287542)

EFO:0004196 viral human hepatitis infection is 
Subclass of:
inflammatory disease
viral disease
liver disease
digestive system infectious disease
which is all good, however, all 4 children have the additional parent  EFO > MONDO:0024294 skin disease caused by infection. This should rather be represented as a symptom with phenotype (hepatitis may cause jaundice). 
- [x] I'll raise with MONDO (done: https://github.com/monarch-initiative/mondo/issues/825), then we need to remove the parent in EFO too.

Finally, we may want to be more consistent in labels:
viral human hepatitis infection
has children
hepatitis A
hepatitis B infection
hepatitis C infection
hepatitis E 
- [x] I propose changing to 'hepatitis X infection' as that disambiguates fully between virus species and disease. Let MONDO know we're doing this in case they wish to do the same (all of their terms are 'hepatitis X') (done, https://github.com/monarch-initiative/mondo/issues/825).

**Comment by zoependlington** [comment]
The hepatitis x infection terms have been updated in the latest MONDO release.
