### ISSUE TITLE
Addition of synonym to "severe acute respiratory syndrome"

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#736]
## Synonyms

SARS-coronavirus 2
SARS-CoV-2
2019 novel coronavirus
COVID-19
2019-nCoV
β-coronavirus

**Comment by d0choa** [comment]
Related to this. I realised that the parent term [coronavirus infectious disease](http://www.ebi.ac.uk/efo/EFO_0007224) looks more appropriate for some of the coronavirus infectious listed above.

In OpenTargets, we want to monitor these terms to investigate the available data. May I ask if there is any plan to create more specific terms for some of these infections. With obvious particular interest on COVID-19.

**Comment by paolaroncaglia** [comment]
@gkos-bio 
@d0choa 
We will
- [ ] Import MONDO_0100096 2019 novel coronavirus infection (see http://purl.obolibrary.org/obo/MONDO_0100096)
- [ ] Ask Mondo to add the missing synonyms "SARS-coronavirus 2", "2019 novel coronavirus", "2019-nCoV", "β-coronavirus" (note, Mondo already added synonyms "SARS-CoV-2" and "severe acute respiratory syndrome coronavirus 2", they'll be visible in their next release as per https://github.com/monarch-initiative/mondo/issues/1216)

I think the above should address both of your requests, but do let me know if you disagree with anything. 
Thanks,
Paola

**Comment by d0choa** [comment]
Looks good to me. Thanks @paolaroncaglia

**Comment by paolaroncaglia** [comment]
@gkos-bio
@d0choa
FYI, the term MONDO_0100096 '2019 novel coronavirus infection', at the coming Mondo release, will also contain additional synonyms and cross-references that we requested (see https://github.com/monarch-initiative/mondo/issues/1216). EFO will ingest all the info at the next EFO release. Mondo also created a child, MONDO:0100116 'pneumonia caused by 2019 novel coronavirus', based on SnomedCT. Making a note here to 
- [ ] Import MONDO:0100116 'pneumonia caused by 2019 novel coronavirus' too, once released from Mondo.

**Comment by paolaroncaglia** [comment]
Note for self: at the next Mondo release, I will also
- [ ] Keep an eye on any new term/resolution coming from https://github.com/monarch-initiative/mondo/issues/1341, and import more Mondo terms if appropriate/necessary.

**Comment by paolaroncaglia** [comment]
More notes for self:
- [ ] I asked Mondo if they'd wish to add a link between covid-19 and SARS (https://github.com/monarch-initiative/mondo/issues/1216#issuecomment-608283463);
- [ ] Mondo is about to create a term for Middle East Respiratory Syndrome (MERS) (https://github.com/monarch-initiative/mondo/issues/1354), EFO will import it as soon as it's ready;
- [ ] These points, and others earlier in this ticket, should cover for everything needed by Open Targets (see http://blog.opentargets.org/2020/03/31/open-targets-in-the-time-of-covid-19/), but take a closer look at the last 3 paragraphs in the blog to see if we can add/look into anything else.
All Mondo tickets above are already labeled as high priority, and so is this EFO one.

**Comment by paolaroncaglia** [comment]
@gkos-bio 
@d0choa 
FYI, the primary label of the Mondo term now in EFO is 'COVID-19' (MONDO:0100096, i.e. no longer '2019 novel coronavirus infection' which stays as a synonym). The term now includes all the requested synonyms and cross-references discussed in this ticket.

**Comment by paolaroncaglia** [comment]
Note for self: only left to do here:
- [ ] Keep an eye on resolution from https://github.com/monarch-initiative/mondo/issues/1355 and see if superclasses of 'coronavirus infectious disease' in EFO need revising.
